{% set name = "choix" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d7d4fa376a119167ad51b629fd423f50356c04ef0c3bf65399e7c7c0ceaf520

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - choix

about:
  home: https://pypi.org/project/choix/
  summary: Inference algorithms for models based on Luce's choice axiom.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
